FROM runpod/pytorch:2.2.0-py3.11-cuda12.1.1

WORKDIR /workspace

COPY requirements.txt /workspace/requirements.txt
RUN pip install --no-cache-dir -r /workspace/requirements.txt

COPY . /workspace

ENV RUNPOD_HANDLER=handler.handler

CMD ["python", "-m", "runpod"]
